//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.Websitepanel.Auth {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://smbsaas/websitepanel/enterpriseserver")]
    [System.SerializableAttribute()]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RoleIdField;
        
        private BusinessLogic.Websitepanel.Auth.UserRole RoleField;
        
        private int StatusIdField;
        
        private BusinessLogic.Websitepanel.Auth.UserStatus StatusField;
        
        private int LoginStatusIdField;
        
        private BusinessLogic.Websitepanel.Auth.UserLoginStatus LoginStatusField;
        
        private int FailedLoginsField;
        
        private int UserIdField;
        
        private int OwnerIdField;
        
        private bool IsPeerField;
        
        private System.DateTime CreatedField;
        
        private System.DateTime ChangedField;
        
        private bool IsDemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstantMessengerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondaryPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondaryEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        private bool HtmlMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        private bool EcommerceEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriberNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalParamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BusinessLogic.Websitepanel.Auth.UserVlan[] VlansField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public BusinessLogic.Websitepanel.Auth.UserRole Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int StatusId {
            get {
                return this.StatusIdField;
            }
            set {
                if ((this.StatusIdField.Equals(value) != true)) {
                    this.StatusIdField = value;
                    this.RaisePropertyChanged("StatusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public BusinessLogic.Websitepanel.Auth.UserStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int LoginStatusId {
            get {
                return this.LoginStatusIdField;
            }
            set {
                if ((this.LoginStatusIdField.Equals(value) != true)) {
                    this.LoginStatusIdField = value;
                    this.RaisePropertyChanged("LoginStatusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public BusinessLogic.Websitepanel.Auth.UserLoginStatus LoginStatus {
            get {
                return this.LoginStatusField;
            }
            set {
                if ((this.LoginStatusField.Equals(value) != true)) {
                    this.LoginStatusField = value;
                    this.RaisePropertyChanged("LoginStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int FailedLogins {
            get {
                return this.FailedLoginsField;
            }
            set {
                if ((this.FailedLoginsField.Equals(value) != true)) {
                    this.FailedLoginsField = value;
                    this.RaisePropertyChanged("FailedLogins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int OwnerId {
            get {
                return this.OwnerIdField;
            }
            set {
                if ((this.OwnerIdField.Equals(value) != true)) {
                    this.OwnerIdField = value;
                    this.RaisePropertyChanged("OwnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public bool IsPeer {
            get {
                return this.IsPeerField;
            }
            set {
                if ((this.IsPeerField.Equals(value) != true)) {
                    this.IsPeerField = value;
                    this.RaisePropertyChanged("IsPeer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime Changed {
            get {
                return this.ChangedField;
            }
            set {
                if ((this.ChangedField.Equals(value) != true)) {
                    this.ChangedField = value;
                    this.RaisePropertyChanged("Changed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool IsDemo {
            get {
                return this.IsDemoField;
            }
            set {
                if ((this.IsDemoField.Equals(value) != true)) {
                    this.IsDemoField = value;
                    this.RaisePropertyChanged("IsDemo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string PrimaryPhone {
            get {
                return this.PrimaryPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryPhoneField, value) != true)) {
                    this.PrimaryPhoneField = value;
                    this.RaisePropertyChanged("PrimaryPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string InstantMessenger {
            get {
                return this.InstantMessengerField;
            }
            set {
                if ((object.ReferenceEquals(this.InstantMessengerField, value) != true)) {
                    this.InstantMessengerField = value;
                    this.RaisePropertyChanged("InstantMessenger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string SecondaryPhone {
            get {
                return this.SecondaryPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondaryPhoneField, value) != true)) {
                    this.SecondaryPhoneField = value;
                    this.RaisePropertyChanged("SecondaryPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string SecondaryEmail {
            get {
                return this.SecondaryEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondaryEmailField, value) != true)) {
                    this.SecondaryEmailField = value;
                    this.RaisePropertyChanged("SecondaryEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=28)]
        public bool HtmlMail {
            get {
                return this.HtmlMailField;
            }
            set {
                if ((this.HtmlMailField.Equals(value) != true)) {
                    this.HtmlMailField = value;
                    this.RaisePropertyChanged("HtmlMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=30)]
        public bool EcommerceEnabled {
            get {
                return this.EcommerceEnabledField;
            }
            set {
                if ((this.EcommerceEnabledField.Equals(value) != true)) {
                    this.EcommerceEnabledField = value;
                    this.RaisePropertyChanged("EcommerceEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string SubscriberNumber {
            get {
                return this.SubscriberNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriberNumberField, value) != true)) {
                    this.SubscriberNumberField = value;
                    this.RaisePropertyChanged("SubscriberNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string AdditionalParams {
            get {
                return this.AdditionalParamsField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalParamsField, value) != true)) {
                    this.AdditionalParamsField = value;
                    this.RaisePropertyChanged("AdditionalParams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public BusinessLogic.Websitepanel.Auth.UserVlan[] Vlans {
            get {
                return this.VlansField;
            }
            set {
                if ((object.ReferenceEquals(this.VlansField, value) != true)) {
                    this.VlansField = value;
                    this.RaisePropertyChanged("Vlans");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRole", Namespace="http://smbsaas/websitepanel/enterpriseserver")]
    public enum UserRole : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Administrator = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reseller = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        User = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResellerCSR = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlatformCSR = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResellerHelpdesk = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlatformHelpdesk = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserStatus", Namespace="http://smbsaas/websitepanel/enterpriseserver")]
    public enum UserStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Suspended = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelled = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserLoginStatus", Namespace="http://smbsaas/websitepanel/enterpriseserver")]
    public enum UserLoginStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enabled = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disabled = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LockedOut = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserVlan", Namespace="http://smbsaas/websitepanel/enterpriseserver")]
    [System.SerializableAttribute()]
    public partial class UserVlan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ushort VLanIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ushort VLanID {
            get {
                return this.VLanIDField;
            }
            set {
                if ((this.VLanIDField.Equals(value) != true)) {
                    this.VLanIDField = value;
                    this.RaisePropertyChanged("VLanID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smbsaas/websitepanel/enterpriseserver", ConfigurationName="Websitepanel.Auth.esAuthenticationSoap")]
    public interface esAuthenticationSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://smbsaas/websitepanel/enterpriseserver is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://smbsaas/websitepanel/enterpriseserver/AuthenticateUser", ReplyAction="*")]
        BusinessLogic.Websitepanel.Auth.AuthenticateUserResponse AuthenticateUser(BusinessLogic.Websitepanel.Auth.AuthenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smbsaas/websitepanel/enterpriseserver/AuthenticateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessLogic.Websitepanel.Auth.AuthenticateUserResponse> AuthenticateUserAsync(BusinessLogic.Websitepanel.Auth.AuthenticateUserRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://smbsaas/websitepanel/enterpriseserver is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://smbsaas/websitepanel/enterpriseserver/GetUserByUsernamePassword", ReplyAction="*")]
        BusinessLogic.Websitepanel.Auth.GetUserByUsernamePasswordResponse GetUserByUsernamePassword(BusinessLogic.Websitepanel.Auth.GetUserByUsernamePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smbsaas/websitepanel/enterpriseserver/GetUserByUsernamePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessLogic.Websitepanel.Auth.GetUserByUsernamePasswordResponse> GetUserByUsernamePasswordAsync(BusinessLogic.Websitepanel.Auth.GetUserByUsernamePasswordRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://smbsaas/websitepanel/enterpriseserver is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://smbsaas/websitepanel/enterpriseserver/ChangeUserPasswordByUsername", ReplyAction="*")]
        BusinessLogic.Websitepanel.Auth.ChangeUserPasswordByUsernameResponse ChangeUserPasswordByUsername(BusinessLogic.Websitepanel.Auth.ChangeUserPasswordByUsernameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smbsaas/websitepanel/enterpriseserver/ChangeUserPasswordByUsername", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessLogic.Websitepanel.Auth.ChangeUserPasswordByUsernameResponse> ChangeUserPasswordByUsernameAsync(BusinessLogic.Websitepanel.Auth.ChangeUserPasswordByUsernameRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://smbsaas/websitepanel/enterpriseserver is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://smbsaas/websitepanel/enterpriseserver/SendPasswordReminder", ReplyAction="*")]
        BusinessLogic.Websitepanel.Auth.SendPasswordReminderResponse SendPasswordReminder(BusinessLogic.Websitepanel.Auth.SendPasswordReminderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smbsaas/websitepanel/enterpriseserver/SendPasswordReminder", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessLogic.Websitepanel.Auth.SendPasswordReminderResponse> SendPasswordReminderAsync(BusinessLogic.Websitepanel.Auth.SendPasswordReminderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smbsaas/websitepanel/enterpriseserver/GetSystemSetupMode", ReplyAction="*")]
        bool GetSystemSetupMode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smbsaas/websitepanel/enterpriseserver/GetSystemSetupMode", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> GetSystemSetupModeAsync();
        
        // CODEGEN: Generating message contract since element name passwordA from namespace http://smbsaas/websitepanel/enterpriseserver is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://smbsaas/websitepanel/enterpriseserver/SetupControlPanelAccounts", ReplyAction="*")]
        BusinessLogic.Websitepanel.Auth.SetupControlPanelAccountsResponse SetupControlPanelAccounts(BusinessLogic.Websitepanel.Auth.SetupControlPanelAccountsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smbsaas/websitepanel/enterpriseserver/SetupControlPanelAccounts", ReplyAction="*")]
        System.Threading.Tasks.Task<BusinessLogic.Websitepanel.Auth.SetupControlPanelAccountsResponse> SetupControlPanelAccountsAsync(BusinessLogic.Websitepanel.Auth.SetupControlPanelAccountsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUser", Namespace="http://smbsaas/websitepanel/enterpriseserver", Order=0)]
        public BusinessLogic.Websitepanel.Auth.AuthenticateUserRequestBody Body;
        
        public AuthenticateUserRequest() {
        }
        
        public AuthenticateUserRequest(BusinessLogic.Websitepanel.Auth.AuthenticateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://smbsaas/websitepanel/enterpriseserver")]
    public partial class AuthenticateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ip;
        
        public AuthenticateUserRequestBody() {
        }
        
        public AuthenticateUserRequestBody(string username, string password, string ip) {
            this.username = username;
            this.password = password;
            this.ip = ip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserResponse", Namespace="http://smbsaas/websitepanel/enterpriseserver", Order=0)]
        public BusinessLogic.Websitepanel.Auth.AuthenticateUserResponseBody Body;
        
        public AuthenticateUserResponse() {
        }
        
        public AuthenticateUserResponse(BusinessLogic.Websitepanel.Auth.AuthenticateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://smbsaas/websitepanel/enterpriseserver")]
    public partial class AuthenticateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AuthenticateUserResult;
        
        public AuthenticateUserResponseBody() {
        }
        
        public AuthenticateUserResponseBody(int AuthenticateUserResult) {
            this.AuthenticateUserResult = AuthenticateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByUsernamePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByUsernamePassword", Namespace="http://smbsaas/websitepanel/enterpriseserver", Order=0)]
        public BusinessLogic.Websitepanel.Auth.GetUserByUsernamePasswordRequestBody Body;
        
        public GetUserByUsernamePasswordRequest() {
        }
        
        public GetUserByUsernamePasswordRequest(BusinessLogic.Websitepanel.Auth.GetUserByUsernamePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://smbsaas/websitepanel/enterpriseserver")]
    public partial class GetUserByUsernamePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ip;
        
        public GetUserByUsernamePasswordRequestBody() {
        }
        
        public GetUserByUsernamePasswordRequestBody(string username, string password, string ip) {
            this.username = username;
            this.password = password;
            this.ip = ip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByUsernamePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByUsernamePasswordResponse", Namespace="http://smbsaas/websitepanel/enterpriseserver", Order=0)]
        public BusinessLogic.Websitepanel.Auth.GetUserByUsernamePasswordResponseBody Body;
        
        public GetUserByUsernamePasswordResponse() {
        }
        
        public GetUserByUsernamePasswordResponse(BusinessLogic.Websitepanel.Auth.GetUserByUsernamePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://smbsaas/websitepanel/enterpriseserver")]
    public partial class GetUserByUsernamePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BusinessLogic.Websitepanel.Auth.UserInfo GetUserByUsernamePasswordResult;
        
        public GetUserByUsernamePasswordResponseBody() {
        }
        
        public GetUserByUsernamePasswordResponseBody(BusinessLogic.Websitepanel.Auth.UserInfo GetUserByUsernamePasswordResult) {
            this.GetUserByUsernamePasswordResult = GetUserByUsernamePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeUserPasswordByUsernameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeUserPasswordByUsername", Namespace="http://smbsaas/websitepanel/enterpriseserver", Order=0)]
        public BusinessLogic.Websitepanel.Auth.ChangeUserPasswordByUsernameRequestBody Body;
        
        public ChangeUserPasswordByUsernameRequest() {
        }
        
        public ChangeUserPasswordByUsernameRequest(BusinessLogic.Websitepanel.Auth.ChangeUserPasswordByUsernameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://smbsaas/websitepanel/enterpriseserver")]
    public partial class ChangeUserPasswordByUsernameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oldPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ip;
        
        public ChangeUserPasswordByUsernameRequestBody() {
        }
        
        public ChangeUserPasswordByUsernameRequestBody(string username, string oldPassword, string newPassword, string ip) {
            this.username = username;
            this.oldPassword = oldPassword;
            this.newPassword = newPassword;
            this.ip = ip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeUserPasswordByUsernameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeUserPasswordByUsernameResponse", Namespace="http://smbsaas/websitepanel/enterpriseserver", Order=0)]
        public BusinessLogic.Websitepanel.Auth.ChangeUserPasswordByUsernameResponseBody Body;
        
        public ChangeUserPasswordByUsernameResponse() {
        }
        
        public ChangeUserPasswordByUsernameResponse(BusinessLogic.Websitepanel.Auth.ChangeUserPasswordByUsernameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://smbsaas/websitepanel/enterpriseserver")]
    public partial class ChangeUserPasswordByUsernameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ChangeUserPasswordByUsernameResult;
        
        public ChangeUserPasswordByUsernameResponseBody() {
        }
        
        public ChangeUserPasswordByUsernameResponseBody(int ChangeUserPasswordByUsernameResult) {
            this.ChangeUserPasswordByUsernameResult = ChangeUserPasswordByUsernameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendPasswordReminderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendPasswordReminder", Namespace="http://smbsaas/websitepanel/enterpriseserver", Order=0)]
        public BusinessLogic.Websitepanel.Auth.SendPasswordReminderRequestBody Body;
        
        public SendPasswordReminderRequest() {
        }
        
        public SendPasswordReminderRequest(BusinessLogic.Websitepanel.Auth.SendPasswordReminderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://smbsaas/websitepanel/enterpriseserver")]
    public partial class SendPasswordReminderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ip;
        
        public SendPasswordReminderRequestBody() {
        }
        
        public SendPasswordReminderRequestBody(string username, string ip) {
            this.username = username;
            this.ip = ip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendPasswordReminderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendPasswordReminderResponse", Namespace="http://smbsaas/websitepanel/enterpriseserver", Order=0)]
        public BusinessLogic.Websitepanel.Auth.SendPasswordReminderResponseBody Body;
        
        public SendPasswordReminderResponse() {
        }
        
        public SendPasswordReminderResponse(BusinessLogic.Websitepanel.Auth.SendPasswordReminderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://smbsaas/websitepanel/enterpriseserver")]
    public partial class SendPasswordReminderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendPasswordReminderResult;
        
        public SendPasswordReminderResponseBody() {
        }
        
        public SendPasswordReminderResponseBody(int SendPasswordReminderResult) {
            this.SendPasswordReminderResult = SendPasswordReminderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetupControlPanelAccountsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetupControlPanelAccounts", Namespace="http://smbsaas/websitepanel/enterpriseserver", Order=0)]
        public BusinessLogic.Websitepanel.Auth.SetupControlPanelAccountsRequestBody Body;
        
        public SetupControlPanelAccountsRequest() {
        }
        
        public SetupControlPanelAccountsRequest(BusinessLogic.Websitepanel.Auth.SetupControlPanelAccountsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://smbsaas/websitepanel/enterpriseserver")]
    public partial class SetupControlPanelAccountsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passwordA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passwordB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ip;
        
        public SetupControlPanelAccountsRequestBody() {
        }
        
        public SetupControlPanelAccountsRequestBody(string passwordA, string passwordB, string ip) {
            this.passwordA = passwordA;
            this.passwordB = passwordB;
            this.ip = ip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetupControlPanelAccountsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetupControlPanelAccountsResponse", Namespace="http://smbsaas/websitepanel/enterpriseserver", Order=0)]
        public BusinessLogic.Websitepanel.Auth.SetupControlPanelAccountsResponseBody Body;
        
        public SetupControlPanelAccountsResponse() {
        }
        
        public SetupControlPanelAccountsResponse(BusinessLogic.Websitepanel.Auth.SetupControlPanelAccountsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://smbsaas/websitepanel/enterpriseserver")]
    public partial class SetupControlPanelAccountsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SetupControlPanelAccountsResult;
        
        public SetupControlPanelAccountsResponseBody() {
        }
        
        public SetupControlPanelAccountsResponseBody(int SetupControlPanelAccountsResult) {
            this.SetupControlPanelAccountsResult = SetupControlPanelAccountsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface esAuthenticationSoapChannel : BusinessLogic.Websitepanel.Auth.esAuthenticationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class esAuthenticationSoapClient : System.ServiceModel.ClientBase<BusinessLogic.Websitepanel.Auth.esAuthenticationSoap>, BusinessLogic.Websitepanel.Auth.esAuthenticationSoap {
        
        public esAuthenticationSoapClient() {
        }
        
        public esAuthenticationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public esAuthenticationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public esAuthenticationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public esAuthenticationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusinessLogic.Websitepanel.Auth.AuthenticateUserResponse BusinessLogic.Websitepanel.Auth.esAuthenticationSoap.AuthenticateUser(BusinessLogic.Websitepanel.Auth.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUser(request);
        }
        
        public int AuthenticateUser(string username, string password, string ip) {
            BusinessLogic.Websitepanel.Auth.AuthenticateUserRequest inValue = new BusinessLogic.Websitepanel.Auth.AuthenticateUserRequest();
            inValue.Body = new BusinessLogic.Websitepanel.Auth.AuthenticateUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.ip = ip;
            BusinessLogic.Websitepanel.Auth.AuthenticateUserResponse retVal = ((BusinessLogic.Websitepanel.Auth.esAuthenticationSoap)(this)).AuthenticateUser(inValue);
            return retVal.Body.AuthenticateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusinessLogic.Websitepanel.Auth.AuthenticateUserResponse> BusinessLogic.Websitepanel.Auth.esAuthenticationSoap.AuthenticateUserAsync(BusinessLogic.Websitepanel.Auth.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusinessLogic.Websitepanel.Auth.AuthenticateUserResponse> AuthenticateUserAsync(string username, string password, string ip) {
            BusinessLogic.Websitepanel.Auth.AuthenticateUserRequest inValue = new BusinessLogic.Websitepanel.Auth.AuthenticateUserRequest();
            inValue.Body = new BusinessLogic.Websitepanel.Auth.AuthenticateUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.ip = ip;
            return ((BusinessLogic.Websitepanel.Auth.esAuthenticationSoap)(this)).AuthenticateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusinessLogic.Websitepanel.Auth.GetUserByUsernamePasswordResponse BusinessLogic.Websitepanel.Auth.esAuthenticationSoap.GetUserByUsernamePassword(BusinessLogic.Websitepanel.Auth.GetUserByUsernamePasswordRequest request) {
            return base.Channel.GetUserByUsernamePassword(request);
        }
        
        public BusinessLogic.Websitepanel.Auth.UserInfo GetUserByUsernamePassword(string username, string password, string ip) {
            BusinessLogic.Websitepanel.Auth.GetUserByUsernamePasswordRequest inValue = new BusinessLogic.Websitepanel.Auth.GetUserByUsernamePasswordRequest();
            inValue.Body = new BusinessLogic.Websitepanel.Auth.GetUserByUsernamePasswordRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.ip = ip;
            BusinessLogic.Websitepanel.Auth.GetUserByUsernamePasswordResponse retVal = ((BusinessLogic.Websitepanel.Auth.esAuthenticationSoap)(this)).GetUserByUsernamePassword(inValue);
            return retVal.Body.GetUserByUsernamePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusinessLogic.Websitepanel.Auth.GetUserByUsernamePasswordResponse> BusinessLogic.Websitepanel.Auth.esAuthenticationSoap.GetUserByUsernamePasswordAsync(BusinessLogic.Websitepanel.Auth.GetUserByUsernamePasswordRequest request) {
            return base.Channel.GetUserByUsernamePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusinessLogic.Websitepanel.Auth.GetUserByUsernamePasswordResponse> GetUserByUsernamePasswordAsync(string username, string password, string ip) {
            BusinessLogic.Websitepanel.Auth.GetUserByUsernamePasswordRequest inValue = new BusinessLogic.Websitepanel.Auth.GetUserByUsernamePasswordRequest();
            inValue.Body = new BusinessLogic.Websitepanel.Auth.GetUserByUsernamePasswordRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.ip = ip;
            return ((BusinessLogic.Websitepanel.Auth.esAuthenticationSoap)(this)).GetUserByUsernamePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusinessLogic.Websitepanel.Auth.ChangeUserPasswordByUsernameResponse BusinessLogic.Websitepanel.Auth.esAuthenticationSoap.ChangeUserPasswordByUsername(BusinessLogic.Websitepanel.Auth.ChangeUserPasswordByUsernameRequest request) {
            return base.Channel.ChangeUserPasswordByUsername(request);
        }
        
        public int ChangeUserPasswordByUsername(string username, string oldPassword, string newPassword, string ip) {
            BusinessLogic.Websitepanel.Auth.ChangeUserPasswordByUsernameRequest inValue = new BusinessLogic.Websitepanel.Auth.ChangeUserPasswordByUsernameRequest();
            inValue.Body = new BusinessLogic.Websitepanel.Auth.ChangeUserPasswordByUsernameRequestBody();
            inValue.Body.username = username;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            inValue.Body.ip = ip;
            BusinessLogic.Websitepanel.Auth.ChangeUserPasswordByUsernameResponse retVal = ((BusinessLogic.Websitepanel.Auth.esAuthenticationSoap)(this)).ChangeUserPasswordByUsername(inValue);
            return retVal.Body.ChangeUserPasswordByUsernameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusinessLogic.Websitepanel.Auth.ChangeUserPasswordByUsernameResponse> BusinessLogic.Websitepanel.Auth.esAuthenticationSoap.ChangeUserPasswordByUsernameAsync(BusinessLogic.Websitepanel.Auth.ChangeUserPasswordByUsernameRequest request) {
            return base.Channel.ChangeUserPasswordByUsernameAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusinessLogic.Websitepanel.Auth.ChangeUserPasswordByUsernameResponse> ChangeUserPasswordByUsernameAsync(string username, string oldPassword, string newPassword, string ip) {
            BusinessLogic.Websitepanel.Auth.ChangeUserPasswordByUsernameRequest inValue = new BusinessLogic.Websitepanel.Auth.ChangeUserPasswordByUsernameRequest();
            inValue.Body = new BusinessLogic.Websitepanel.Auth.ChangeUserPasswordByUsernameRequestBody();
            inValue.Body.username = username;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            inValue.Body.ip = ip;
            return ((BusinessLogic.Websitepanel.Auth.esAuthenticationSoap)(this)).ChangeUserPasswordByUsernameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusinessLogic.Websitepanel.Auth.SendPasswordReminderResponse BusinessLogic.Websitepanel.Auth.esAuthenticationSoap.SendPasswordReminder(BusinessLogic.Websitepanel.Auth.SendPasswordReminderRequest request) {
            return base.Channel.SendPasswordReminder(request);
        }
        
        public int SendPasswordReminder(string username, string ip) {
            BusinessLogic.Websitepanel.Auth.SendPasswordReminderRequest inValue = new BusinessLogic.Websitepanel.Auth.SendPasswordReminderRequest();
            inValue.Body = new BusinessLogic.Websitepanel.Auth.SendPasswordReminderRequestBody();
            inValue.Body.username = username;
            inValue.Body.ip = ip;
            BusinessLogic.Websitepanel.Auth.SendPasswordReminderResponse retVal = ((BusinessLogic.Websitepanel.Auth.esAuthenticationSoap)(this)).SendPasswordReminder(inValue);
            return retVal.Body.SendPasswordReminderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusinessLogic.Websitepanel.Auth.SendPasswordReminderResponse> BusinessLogic.Websitepanel.Auth.esAuthenticationSoap.SendPasswordReminderAsync(BusinessLogic.Websitepanel.Auth.SendPasswordReminderRequest request) {
            return base.Channel.SendPasswordReminderAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusinessLogic.Websitepanel.Auth.SendPasswordReminderResponse> SendPasswordReminderAsync(string username, string ip) {
            BusinessLogic.Websitepanel.Auth.SendPasswordReminderRequest inValue = new BusinessLogic.Websitepanel.Auth.SendPasswordReminderRequest();
            inValue.Body = new BusinessLogic.Websitepanel.Auth.SendPasswordReminderRequestBody();
            inValue.Body.username = username;
            inValue.Body.ip = ip;
            return ((BusinessLogic.Websitepanel.Auth.esAuthenticationSoap)(this)).SendPasswordReminderAsync(inValue);
        }
        
        public bool GetSystemSetupMode() {
            return base.Channel.GetSystemSetupMode();
        }
        
        public System.Threading.Tasks.Task<bool> GetSystemSetupModeAsync() {
            return base.Channel.GetSystemSetupModeAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusinessLogic.Websitepanel.Auth.SetupControlPanelAccountsResponse BusinessLogic.Websitepanel.Auth.esAuthenticationSoap.SetupControlPanelAccounts(BusinessLogic.Websitepanel.Auth.SetupControlPanelAccountsRequest request) {
            return base.Channel.SetupControlPanelAccounts(request);
        }
        
        public int SetupControlPanelAccounts(string passwordA, string passwordB, string ip) {
            BusinessLogic.Websitepanel.Auth.SetupControlPanelAccountsRequest inValue = new BusinessLogic.Websitepanel.Auth.SetupControlPanelAccountsRequest();
            inValue.Body = new BusinessLogic.Websitepanel.Auth.SetupControlPanelAccountsRequestBody();
            inValue.Body.passwordA = passwordA;
            inValue.Body.passwordB = passwordB;
            inValue.Body.ip = ip;
            BusinessLogic.Websitepanel.Auth.SetupControlPanelAccountsResponse retVal = ((BusinessLogic.Websitepanel.Auth.esAuthenticationSoap)(this)).SetupControlPanelAccounts(inValue);
            return retVal.Body.SetupControlPanelAccountsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusinessLogic.Websitepanel.Auth.SetupControlPanelAccountsResponse> BusinessLogic.Websitepanel.Auth.esAuthenticationSoap.SetupControlPanelAccountsAsync(BusinessLogic.Websitepanel.Auth.SetupControlPanelAccountsRequest request) {
            return base.Channel.SetupControlPanelAccountsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusinessLogic.Websitepanel.Auth.SetupControlPanelAccountsResponse> SetupControlPanelAccountsAsync(string passwordA, string passwordB, string ip) {
            BusinessLogic.Websitepanel.Auth.SetupControlPanelAccountsRequest inValue = new BusinessLogic.Websitepanel.Auth.SetupControlPanelAccountsRequest();
            inValue.Body = new BusinessLogic.Websitepanel.Auth.SetupControlPanelAccountsRequestBody();
            inValue.Body.passwordA = passwordA;
            inValue.Body.passwordB = passwordB;
            inValue.Body.ip = ip;
            return ((BusinessLogic.Websitepanel.Auth.esAuthenticationSoap)(this)).SetupControlPanelAccountsAsync(inValue);
        }
    }
}
